@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Mar 31 11:51:46 +0100 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim mux21_1_TB_behav -key {Behavioral:sim_1:Functional:mux21_1_TB} -tclbatch mux21_1_TB.tcl -view C:/2023/vicilogic/HDLGenTop/HDLGen/User_Projects/combinational/mux21_1/verilog/AMDprj/mux21_1_TB_behav.wcfg -log simulate.log"
call xsim  mux21_1_TB_behav -key {Behavioral:sim_1:Functional:mux21_1_TB} -tclbatch mux21_1_TB.tcl -view C:/2023/vicilogic/HDLGenTop/HDLGen/User_Projects/combinational/mux21_1/verilog/AMDprj/mux21_1_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
