@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Mar 29 13:45:30 +0100 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto fdb91471379d412ba7e8621f5fe0c6d0 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot ADD2_TB_behav xil_defaultlib.ADD2_TB -log elaborate.log"
call xelab  -wto fdb91471379d412ba7e8621f5fe0c6d0 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot ADD2_TB_behav xil_defaultlib.ADD2_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
