/* 
   Header section
   Generated by HDLGen, Github https://github.com/abishek-bupathi/HDLGen
   Reference: https://tinyurl.com/VerilogTips 
      
   Component Name : mux21_1
   Title          : 2-to-1 mux, 1-bit data
*/

/*
   Description
   sel is datapath control signal
   muxOut = muxIn0 when sel  = 0
   muxOut = muxIn1 when sel  = 1 

   Author(s)      : Fearghal Morgan
   Company        : University of Galway
   Email          : fearghal.morgan@universityofgalway.ie
   Date           : 13/3/2023
*/

/*
   entity signal dictionary
   sel	datapath control signal
   muxIn1	datapath 1 input signal
   muxIn0	datapath 0 input signal
   muxOut	data out signal
*/

/* 
   internal signal dictionary
   None
*/

// FM No library declarations required //

// module declaration                
module mux21_1(
		sel, 
		muxIn1,
		muxIn0,
		muxOut
	);

// <FM> outdent port definitions to left margin
// Port definitions
input  sel;
input  muxIn1;
input  muxIn0;
	
output muxOut;
reg muxOut;

// FM No architecture statement required 

/* Internal signal declarations
   None
*/

// <FM> don't include any reference to component declarations in Verilog
// <FM> No architecture begin statement required 

// muxOut_a 
always @(sel or muxIn1 or muxIn0)
  begin : muxOut_a
    // Complete the process if required and delete this comment
    muxOut <= muxIn0; // default assignment
    if (sel) 
		begin
            muxOut <= muxIn1;  
		end
  end
    
endmodule