del /s *.log
del /s *.jou
del /s libPortability.dll
del /s *.dbg
del /s *.vho
del /s *.pad
del /s *.par
del /s *.didat
del /s *.log_backup
del /s *.unroutes
del /s *.map
del /s *.cmd
del /s *.csv
del /s *.xmsgs
del /s *.ptwx
del /s *.xrpt
del /s *.bgn
del /s *.pcf
del /s *.twx
del /s *.twr
del /s *.drc
del /s *.ngm
del /s *.ngo
del /s *.srp
del /s *.ipf
del /s *.mrp
del /s *.vdb
del /s *.obj
del /s *.lck
del /s *.svf
del /s *.xreport
del /s *.tmp
del /s *.gise
del /s *.sh
del /s *.ngr
del /s *.stx
del /s *.ut
del /s *.syr
del /s job*.bat
del /s webtalk_pa.xml
del /s simulate.bat
del /s runme.bat
del /s elaborate.bat
del /s compile.bat
del /s htr.txt
del /s rundef.js
del /s ISEWrap.js