webtalk_init -webtalk_dir C:/2023/vicilogic/HDLGenTop/HDLGen/User_Projects/combinational/mux21_1/verilog/AMDprj/mux21_1.sim/sim_1/behav/xsim/xsim.dir/mux21_1_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 31 12:01:05 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "53c53263-411c-4f7f-b6ce-75c07498a468" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2108598bb2c045bd92eb97f1e9e1f8e1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-1235U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6568_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3686544719 -regid "" -xml C:/2023/vicilogic/HDLGenTop/HDLGen/User_Projects/combinational/mux21_1/verilog/AMDprj/mux21_1.sim/sim_1/behav/xsim/xsim.dir/mux21_1_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/2023/vicilogic/HDLGenTop/HDLGen/User_Projects/combinational/mux21_1/verilog/AMDprj/mux21_1.sim/sim_1/behav/xsim/xsim.dir/mux21_1_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/2023/vicilogic/HDLGenTop/HDLGen/User_Projects/combinational/mux21_1/verilog/AMDprj/mux21_1.sim/sim_1/behav/xsim/xsim.dir/mux21_1_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
